name: EssentialsM
version: 1.0-SNAPSHOT
main: ch.gamepowerx.essentialsm.EssentialsM
api-version: 1.15
author: CraftingDragon007

commands:
  gamemode:
    description: Mit diesem Command kanst du deinen Spielmodus ändern!
    aliases: [gm]
    permission: essentialsm.gamemode
    usage: /gamemode (surival,creative,adventure,spectator)
  heal:
    description: Mit diesem Command kannst du dich heilen!
    permission: essentialsm.heal
    usage: /heal <Spieler>
  teleport:
    description: Mit diesem Command kannst du dich teleportieren!
    aliases: [tp,tpo]
    permission: essentialsm.teleport
    usage: /teleport (Spieler|Koordinaten) <Spieler|Koordinaten>
  tpohere:
    description: Mit diesem Command kannst du Spieler zu dir teleportieren!
    aliases: [tphere,teleporthere]
    permission: essentials.teleport
    usage: /tpohere (Spieler)
  fly:
    description: Mit diesem Command kannst du Fliegen!
    permission: essentialsm.fly
    usage: /fly <Spieler>
  speed:
    description: Mit diesem Command kannst du deine Geschwindigkeit ändern!
    permission: essentialsm.speed
    usage: /speed (Zahl|Spieler) <Zahl>
  killall:
    description: Tötet alle ausgweählten Entitäten!
    permission: essentialsm.killall
    usage: /killall (Entitäten) <Welt>
  tpa:
    description: Sendet einem Spieler eine Teleportierungsanfrage!
    permission: essentialsm.tpa
    usage: /tpa (Spieler)
  tpaaccept:
    description: Nimmt eine Teleportierungsanfrage an!
    permission: essentials.tpa
    usage: /tpaccept (Spieler)
  tpadeny:
    description: Lehnt oder bricht eine Teleportierungsanfrage ab!
    permission: essentialsm.tpa
    usage: /tpadeny (Spieler)
  invsee:
    description: Greife auf Inventare anderer Spieler zu!
    permission: essentialsm.invsee
    usage: /invsee (Spieler)
  msg:
    description: Sende Nachrichten an andere Spieler!
    permission: essentialsm.msg
    usage: /msg (Spieler) (Nachricht)
  respond:
    description: Antworte auf eine Nachricht!
    aliases: [r]
    permission: essentialsm.msg
    usage: /r (Nachricht)

permissions:
  essentialsm.*:
    description: Zugriff auf alle EssentialsM Commands!
    default: op
    children:
      essentialsm.gamemode: true
      essentialsm.heal: true
      essentialsm.teleport: true
      essentialsm.fly: true
      essentialsm.speed: true
  essentialsm.gamemode:
    description: Zugriff auf alle Gamemodes!
    default: op
  essentialsm.heal:
    description: Zugriff auf /heal
    default: op
  essentialsm.teleport:
    description: Zugriff auf /teleport
    default: op
  essentialsm.fly:
    description: Zugriff auf /fly
    default: op
  essentialsm.speed:
    description: Zugriff auf /speed
    default: op
  essentialsm.killall:
    description: Zugriff auf /killall
    default: op
  essentialsm.tpa:
    description: Zugriff auf /tpa
    default: not op
  essentialsm.invsee:
    descripion: Zugriff auf /invsee
    default: op
  essentialsm.msg:
    description: Zugriff auf /msg
    default: not op