name: EssentialsM
version: ${project.version}
main: ch.gamepowerx.essentialsm.EssentialsM
api-version: 1.15
author: CraftingDragon007
softdepend:
  - Notes

commands:
  gamemode:
    description: Mit diesem Command kanst du deinen Spielmodus ändern!
    aliases: [gm]
    permission: essentialsm.Gamemode
    usage: /Gamemode (surival,creative,adventure,spectator)
  heal:
    description: Mit diesem Command kannst du dich heilen!
    permission: essentialsm.Heal
    usage: /Heal <Spieler>
  teleport:
    description: Mit diesem Command kannst du dich teleportieren!
    aliases: [tp,tpo]
    permission: essentialsm.Teleport
    usage: /Teleport (Spieler|Koordinaten) <Spieler|Koordinaten>
  tpohere:
    description: Mit diesem Command kannst du Spieler zu dir teleportieren!
    aliases: [tphere,teleporthere]
    permission: essentials.Teleport
    usage: /Tpohere (Spieler)
  fly:
    description: Mit diesem Command kannst du Fliegen!
    permission: essentialsm.Fly
    usage: /Fly <Spieler>
  speed:
    description: Mit diesem Command kannst du deine Geschwindigkeit ändern!
    permission: essentialsm.Speed
    usage: /Speed (Zahl|Spieler) <Zahl>
  kill:
    description: Tötet die ausgweählten Entitäten oder Spieler!
    permission: essentialsm.Kill
    usage: /Kill (Spieler|Entität/en)
  killall:
    description: Tötet alle ausgweählten Entitäten!
    permission: essentialsm.Killall
    usage: /Killall (Entitäten) <Welt>
  tpa:
    description: Sendet einem Spieler eine Teleportierungsanfrage!
    permission: essentialsm.Tpa
    usage: /Tpa (Spieler)
  tpaaccept:
    description: Nimmt eine Teleportierungsanfrage an!
    permission: essentials.Tpa
    usage: /tpaccept (Spieler)
  tpadeny:
    description: Lehnt oder bricht eine Teleportierungsanfrage ab!
    permission: essentialsm.Tpa
    usage: /Tpadeny (Spieler)
  invsee:
    description: Greife auf Inventare anderer Spieler zu!
    permission: essentialsm.Invsee
    usage: /Invsee (Spieler)
  msg:
    description: Sende Nachrichten an andere Spieler!
    permission: essentialsm.Msg
    usage: /Msg (Spieler) (Nachricht)
  respond:
    description: Antworte auf eine Nachricht!
    aliases: [r]
    permission: essentialsm.Msg
    usage: /r (Nachricht)
  spawnmob:
    description: Spawnt einen oder mehrere Mobs
    permission: essentialsm.spawnmob
    usage: /spawnmob (Typ) <Anzahl>
  tpall:
    description: Teleportiert alle Spieler zu dir!
    permission: essentialsm.tpall
    usage: /tpall <Spieler>
  gmc:
    description: Setzt dich in den Gamemode Creative
    permission: essentialsm.Gamemode
    usage: /gmc <Spieler>
  gms:
    description: Setzt dich in den Gamemode Survival
    permission: essentialsm.Gamemode
    usage: /gms <Spieler>
  gma:
    description: Setzt dich in den Gamemode Adventure
    permission: essentialsm.Gamemode
    usage: /gma <Spieler>
  gmsp:
    description: Setzt dich in den Gamemode Spectator
    permission: essentialsm.Gamemode
    usage: /gmsp <Spieler>
  ever:
    description: Zeigt dir Informationen zu Essentialsm an
    permission: essentialsm.version
    usage: /ever
    aliases:
      - essentialsmversion

permissions:
  essentialsm.*:
    description: Zugriff auf alle EssentialsM Commands!
    default: op
    children:
      essentialsm.gamemode: true
      essentialsm.heal: true
      essentialsm.teleport: true
      essentialsm.fly: true
      essentialsm.speed: true
      essentialsm.tpa: true
      essentialsm.killall: true
      essentialsm.invsee: true
      essentialsm.msg: true
      essentialsm.spawnmob: true
      essentialsm.tpall: true
  essentialsm.gamemode:
    description: Zugriff auf alle Gamemodes!
    default: op
  essentialsm.heal:
    description: Zugriff auf /Heal
    default: op
  essentialsm.teleport:
    description: Zugriff auf /Teleport
    default: op
  essentialsm.fly:
    description: Zugriff auf /Fly
    default: op
  essentialsm.speed:
    description: Zugriff auf /Speed
    default: op
  essentialsm.kill:
    description: Zugriff auf /kill
    default: op
  essentialsm.killall:
    description: Zugriff auf /Killall
    default: op
  essentialsm.tpa:
    description: Zugriff auf /Tpa
    default: op
  essentialsm.invsee:
    descripion: Zugriff auf /Invsee
    default: op
  essentialsm.msg:
    description: Zugriff auf /Msg
    default: not op
  essentialsm.spawnmob:
    description: Zugriff auf /spawnmob
    default: op
  essentialsm.tpall:
    description: Zugriff auf /tpall
    default: op
  essentialsm.version:
    description: Zugriff auf /ever
    default: op